[webservers]
zhouy1 ansible_host=10.16.201.164 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy2 ansible_host=10.16.201.40 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy3 ansible_host=10.16.201.20 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy4 ansible_host=10.16.201.193 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy5 ansible_host=10.16.201.201 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy6 ansible_host=10.16.201.153 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy7 ansible_host=10.16.201.124 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy8 ansible_host=10.16.201.18 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy9 ansible_host=10.16.201.217 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3
zhouy10 ansible_host=10.16.201.163 ansible_user=root ansible_python_interpreter=/dpc-zhouy/zhouy/miniconda3/envs/py311/bin/python3